const DEMO_NEWS=[
{id:"1",slug:"pembangunan-infrastruktur-kawasan-timur",category:"Nasional",title:"Pemerintah Percepat Pembangunan Infrastruktur di Kawasan Timur",date:"Contoh tanggal",summary:"Contoh ringkasan artikel. Ganti dengan berita yang telah diverifikasi sebelum publikasi.",image:"https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1200&q=80",body:"Ini adalah konten demonstrasi, bukan laporan faktual. Ganti dengan artikel yang telah diperiksa redaksi."},
{id:"2",slug:"perkembangan-ekonomi-daerah",category:"Ekonomi",title:"Perkembangan Ekonomi Daerah Menjadi Perhatian Masyarakat",date:"Contoh tanggal",summary:"Contoh artikel untuk menguji tata letak kategori dan daftar berita.",image:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",body:"Konten demo. Jangan tayangkan sebagai berita nyata tanpa verifikasi."},
{id:"3",slug:"pendidikan-dan-inovasi",category:"Pendidikan",title:"Inovasi Pendidikan dan Kegiatan Sekolah",date:"Contoh tanggal",summary:"Contoh tampilan berita pendidikan.",image:"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80",body:"Konten demo. Jangan tayangkan sebagai berita nyata tanpa verifikasi."}
];
const $=s=>document.querySelector(s);
function header(){const el=$("#site-header");if(!el)return;el.innerHTML=`<header class="site-header"><div class="container"><div class="topbar"><a class="brand" href="index.html"><span class="brand-mark">LB</span><span>LAPOR <b>BERITA</b><span class="tagline">Dari Masyarakat, Untuk Masyarakat</span></span></a><div class="top-actions"><a href="pencarian.html">⌕ Cari</a><a class="button button-red" href="laporkan-berita.html">Laporkan Berita</a></div></div><nav class="nav"><a href="index.html">Beranda</a><a href="berita.html">Berita</a><a href="kategori.html?nama=Nasional">Nasional</a><a href="kategori.html?nama=Daerah">Daerah</a><a href="kategori.html?nama=Politik">Politik</a><a href="kategori.html?nama=Ekonomi">Ekonomi</a><a href="kategori.html?nama=Pendidikan">Pendidikan</a><a href="tentang.html">Tentang</a><a href="kontak.html">Kontak</a></nav></div></header>`}
function footer(){const el=$("#site-footer");if(!el)return;el.innerHTML=`<footer class="site-footer"><div class="container footer-grid"><div><div class="brand"><span class="brand-mark">LB</span><span>LAPOR BERITA</span></div><p>Dari Masyarakat, Untuk Masyarakat.</p><p class="small">Portal contoh. Lengkapi identitas dan kontak redaksi sebelum peluncuran.</p></div><div class="footer-links"><b>Informasi</b><a href="tentang.html">Tentang Kami</a><a href="pedoman-media.html">Pedoman Pemberitaan</a><a href="kebijakan-privasi.html">Kebijakan Privasi</a></div><div class="footer-links"><b>Layanan</b><a href="laporkan-berita.html">Laporkan Berita</a><a href="koreksi-hak-jawab.html">Koreksi dan Hak Jawab</a><a href="kontak.html">Kontak Redaksi</a></div></div></footer>`}
function card(n){return `<article class="news-card"><a href="artikel.html?slug=${encodeURIComponent(n.slug)}"><img src="${n.image}" alt="" loading="lazy"><div class="news-card-body"><div class="category">${n.category}</div><h3>${n.title}</h3><div class="meta">${n.date} · Redaksi Lapor Berita</div><p>${n.summary}</p></div></a></article>`}
function render(){const h=$("#headline");if(h){const n=DEMO_NEWS[0];h.innerHTML=`<img src="${n.image}" alt="" fetchpriority="high"><div class="headline-body"><div class="category">${n.category}</div><h1><a href="artikel.html?slug=${n.slug}">${n.title}</a></h1><div class="meta">${n.date} · Redaksi Lapor Berita</div><p>${n.summary}</p></div>`;$("#side-news").innerHTML=DEMO_NEWS.slice(1).map(n=>`<article class="side-item"><img src="${n.image}" alt="" loading="lazy"><div><div class="category">${n.category}</div><h3><a href="artikel.html?slug=${n.slug}">${n.title}</a></h3><div class="meta">${n.date}</div></div></article>`).join("")}
const all=$("#all-news");if(all)all.innerHTML=DEMO_NEWS.map(card).join("");
const feat=$("#featured-news");if(feat)feat.innerHTML=DEMO_NEWS.map(card).join("");
const detail=$("#article-detail");if(detail){const slug=new URLSearchParams(location.search).get("slug");const n=DEMO_NEWS.find(x=>x.slug===slug)||DEMO_NEWS[0];document.title=n.title+" — Lapor Berita";detail.innerHTML=`<div class="category">${n.category}</div><h1>${n.title}</h1><p class="meta">${n.date} · Redaksi Lapor Berita</p><img style="width:100%;max-height:500px;object-fit:cover;border-radius:12px" src="${n.image}" alt=""><p class="muted">${n.summary}</p><div style="max-width:780px;font-size:1.08rem"><p>${n.body}</p><p><b>Catatan:</b> artikel ini adalah konten demonstrasi dan bukan berita faktual.</p></div>`}
const cat=$("#category-news");if(cat){const name=new URLSearchParams(location.search).get("nama")||"Nasional";$("#category-title").textContent="Kategori: "+name;cat.innerHTML=DEMO_NEWS.filter(n=>n.category.toLowerCase()===name.toLowerCase()).map(card).join("")||"<p>Belum ada berita pada kategori ini.</p>"}
const adminNews=$("#admin-demo-news");if(adminNews)adminNews.innerHTML=`<table><thead><tr><th>Judul</th><th>Kategori</th><th>Status</th></tr></thead><tbody>${DEMO_NEWS.map(n=>`<tr><td>${n.title}</td><td>${n.category}</td><td>DEMO</td></tr>`).join("")}</tbody></table>`;
const sf=$("#search-form");if(sf){sf.addEventListener("submit",e=>{e.preventDefault();const q=$("#q").value.toLowerCase();$("#search-results").innerHTML=DEMO_NEWS.filter(n=>(n.title+" "+n.summary+" "+n.category).toLowerCase().includes(q)).map(card).join("")||"<p>Tidak ada hasil pada data demo.</p>"})}
const rf=$("#report-form");if(rf)rf.addEventListener("submit",e=>{e.preventDefault();$("#report-message").textContent="Ini hanya prototipe. Laporan tidak dikirim atau disimpan. Hubungkan backend aman sebelum digunakan."});
}
header();footer();render();